on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: docker-compose-profile-menu.exe
            asset_name: docker-compose-profile-menu-windows-x86_64
          - os: ubuntu-latest
            artifact_name: docker-compose-profile-menu
            asset_name: docker-compose-profile-menu-linux-x86_64
          - os: macos-latest
            artifact_name: docker-compose-profile-menu
            asset_name: docker-compose-profile-menu-apple-x86_64
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
